---
- name: Create sonar configuration file
  template:
    src: "sonar.properties.j2"
    dest: "/opt/sonar/conf/sonar.properties"
    owner: sonar
    group: sonar
    mode: 0600
    backup: true
  notify: restart sonar
