---
- include_tasks: 01-install.yml
  tags: ['sonarqube','sonarqube-install']
- include_tasks: 02-configure.yml
  tags: ['sonarqube','sonarqube-configure']
- include_tasks: 03-service.yml
  tags: ['sonarqube','sonarqube-service']
