---
- name: Include 01
  include_tasks: 01-install.yml
  tags: ['sonarqube','sonarqube-install']

- name: Include 02
  include_tasks: 02-configure.yml
  tags: ['sonarqube','sonarqube-configure']

- name: Include 03
  include_tasks: 03-service.yml
  tags: ['sonarqube','sonarqube-service']
