---
# tasks file for SonarQube

- name: Get SonarQube Repo
  yum_repository:
    name: SonaQube
    description: SonarQube Repo
    baseurl: http://downloads.sourceforge.net/project/sonar-pkg/rpm
    gpgcheck: no

- name: Create sonar configuration file
  template:
    src: "sonar.properties.j2"
    dest: "/opt/sonar/conf/sonar.properties"
    owner: root
    group: root
    mode: 0644
    backup: true

- name: Install Required Packages
  package:
    name: "{{item}}"
    state: present
  with_items:
       - sonar

- name: Start Required Services
  service:
    name: "{{item}}"
    state: started
    enabled: yes
  with_items:
       - sonar
